# Generated by Django 5.1.6 on 2025-04-05 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_recipe_image_recipeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.recipeimage'),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='recipes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.recipe'),
        ),
    ]
