# Generated by Django 5.1.6 on 2025-04-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_remove_recipeimage_recipe_recipe_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
